// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "PodNotes",
    platforms: [
        .iOS("26.0")
    ],
    products: [
        .iOSApplication(
            name: "PodNotes",
            targets: ["PodNotes"],
            bundleIdentifier: "com.romanus.PodNotes",
            teamIdentifier: "YM7PP9LQJF",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "PodNotes",
            path: "Sources"
        )
    ]
)