// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "PodNotes",
    platforms: [
        .iOS("26.0")
    ],
    targets: [
        .executableTarget(
            name: "PodNotes",
            path: "Sources"
        )
    ]
)

